module reference_interfaces {
  module msg {
    module TransmissionStats_Constants {
      const uint64 NODE_NAME_LENGTH = 56;
    };
    struct TransmissionStats { // 64 bytes
      uint64 timestamp;
      char  node_name[56];
    };
  };
};
